# Generated by Django 4.2.2 on 2023-07-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('file_path', models.FilePathField()),
                ('ip', models.GenericIPAddressField()),
                ('integer', models.IntegerField()),
                ('float', models.FloatField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('time_now', models.TimeField()),
            ],
        ),
    ]
