# Generated by Django 4.2.2 on 2023-07-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_testvalidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testvalidation',
            name='file_path',
        ),
    ]
